name: build

on: [push]

env:
  TAG_GHCR: mrc-ide/wodin-base-image

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: ci-env
        name: Setup Environment
        shell: bash
        run: |
          if [ "${{github.event_name}}" = "pull_request" ];
          then
            long_sha=${{ github.event.pull_request.head.sha }}
            echo "CI_BRANCH=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            long_sha=${GITHUB_SHA}
            echo "CI_BRANCH=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
          echo "CI_SHA=${long_sha:0:7}" >> $GITHUB_OUTPUT

      - name: Build and push docker
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{env.TAG_GHCR}}:${{steps.ci-env.outputs.CI_SHA}}
            ghcr.io/${{env.TAG_GHCR}}:${{steps.ci-env.outputs.CI_BRANCH}}